import Head from 'next/head'
import Image from 'next/image'
import Editor from '@monaco-editor/react'

export default function Home() {
  const handleChange = (val: string | undefined, event: any) => {
		console.log(val)
	}

	const value = `* {
    color: red;
  }`

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Editor
				language='css'
				theme='vs-dark'
				height='80vh'
				onChange={handleChange}
				value={value}
			/>
      </main>
    </>
  )
}
